name: ML Pipeline

on:
  push:
    branches:
      - main

jobs:
  run-ml-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy pandas scikit-learn matplotlib mlflow jupyter nbconvert joblib

      - name: Convert Notebook to Python script
        run: |
          jupyter nbconvert --to python forest_cover_type.ipynb --output forest_cover_type.py

      - name: Run Converted Python Script
        run: |
          python forest_cover_type.py

      - name: Build Docker Image
        run: |
          docker build -t forest-cover-type:latest .
